<?php

// public/add_product_handler.php
require_once '../src/ProductManager.php';
require_once '../src/Product.php'; // Make sure this path is correct

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Assuming you have form validation and sanitization here
    $name = $_POST['name'];
    $category = $_POST['category']; // Category captured from form input
    $price = $_POST['price'];
    $description = $_POST['description'];

    // Directly create a Product object. Adjust according to your Product class constructor
    // Assuming the constructor doesn't require an ID and it's automatically generated by your database
    $product = new Product(null, $name, $price, $description, $category);

    $productManager = new ProductManager();
    $productId = $productManager->addProduct($product);

    if ($productId) {
        echo "Product added successfully. Product ID is: " . $productId;
        // Optionally redirect to a confirmation page or back to the form
        // header('Location: success_page.php');
    } else {
        echo "Failed to add the product.";
        // Handle the error accordingly
    }

    echo '<a href="add_product.php"><button type="button">Add Another Product</button></a>';
}
?>
